### Loading dataset

In [1]:
import pandas as pd 
df = pd.read_csv("loan_risk_prediction_dataset.csv")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              5000 non-null   int64
 1   Income           4804 non-null   float64
 2   LoanAmount       5000 non-null   float64
 3   CreditScore      4806 non-null   float64
 4   YearsExperience  5000 non-null   int64
 5   Gender           5000 non-null   str
 6   Education        4802 non-null   str
 7   City             5000 non-null   str
 8   EmploymentType   5000 non-null   str
 9   LoanApproved     5000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 544.3 KB

In [3]:
df.head()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,NaN,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0

In [4]:
df.dtypes

Age                  int64
Income             float64
LoanAmount         float64
CreditScore        float64
YearsExperience      int64
Gender                 str
Education              str
City                   str
EmploymentType         str
LoanApproved         int64
dtype: object

In [5]:
df.isnull()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,True,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,True,False,False,False

In [6]:
df.shape

(5000, 10)

In [7]:
round((df.isnull().sum() / df.shape[0]) * 100, 2)

Age                0.00
Income             3.92
LoanAmount         0.00
CreditScore        3.88
YearsExperience    0.00
Gender             0.00
Education          3.96
City               0.00
EmploymentType     0.00
LoanApproved       0.00
dtype: float64

In [8]:
df.columns = df.columns.str.strip()

In [9]:
df.fillna({
    'Income': df['Income'].median(),
    'CreditScore': df['CreditScore'].median(),
    'Education': df['Education'].mode()[0]
}, inplace=True)

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,Bachelors,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0
...,...,...,...,...,...,...,...,...,...,...
4995,24,36780.0,23383.0,579.0,23,Male,Masters,Houston,Salaried,0
4996,66,99146.0,9760.0,306.0,14,Male,PhD,New York,Unemployed,0
4997,26,58100.0,18230.0,311.0,10,Female,High School,San Francisco,Self-Employed,0
4998,53,58513.0,12373.0,813.0,23,Male,PhD,Houston,Salaried,1
4999,36,58928.0,23615.0,648.0,10,Male,Bachelors,New York,Self-Employed,1

In [10]:
df.isnull().sum()

Age                0
Income             0
LoanAmount         0
CreditScore        0
YearsExperience    0
Gender             0
Education          0
City               0
EmploymentType     0
LoanApproved       0
dtype: int64

In [11]:
print(df.duplicated().sum())

0

In [12]:
(df['Income'] < 0).sum()

np.int64(3)

In [13]:
df = df[df['Income'] >= 0]

In [14]:
(df['Income'] < 0).sum()

np.int64(0)

In [15]:
(df['Age'] <= 0).sum()

np.int64(0)

In [16]:
(df['CreditScore'] < 0).sum()

np.int64(0)

In [17]:
(df['YearsExperience'] < 0).sum()

np.int64(0)

In [18]:
(df['LoanAmount'] < 0).sum()

np.int64(28)

In [19]:
df = df[df['LoanAmount'] >= 0]

In [20]:
(df['LoanAmount'] < 0).sum()

np.int64(0)

In [21]:
df['Education'].unique()

<ArrowStringArray>
['High School', 'PhD', 'Bachelors', 'Masters']
Length: 4, dtype: str

In [22]:
df['LoanApproved'].unique()

array([0, 1])

In [23]:
df['Gender'].unique()

<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

In [24]:
df.describe()

,Age,Income,LoanAmount,CreditScore,YearsExperience,LoanApproved
count,4969.000000,4969.000000,4969.000000,4969.000000,4969.000000,4969.000000
mean,43.570739,49753.186355,20002.458040,575.365265,19.590662,0.230831
std,14.923863,14724.226918,7884.595787,157.405958,11.521067,0.421407
min,18.000000,129.000000,4.000000,300.000000,0.000000,0.000000
25%,31.000000,40078.000000,14546.000000,439.000000,10.000000,0.000000
50%,43.000000,49488.000000,19885.000000,579.000000,20.000000,0.000000
75%,56.000000,59426.000000,25374.000000,705.000000,29.000000,0.000000
max,69.000000,99146.000000,48353.000000,849.000000,39.000000,1.000000

In [25]:
df.to_csv("cleaned_loan_data.csv", index=False)